### ISSUE TITLE
Importing taxonomy.qza classified with SILVA

### ISSUE THREAD

**Issue by aj-kozik** [jbisanz/qiime2R#11]
Hi,

When I use qza_to_phyloseq for taxonomy artifacts called with Greengenes, the resulting phyloseq object has the taxonomy parsed correctly. However, I need to analyze artifacts called with SILVA and the qza_to_phyloseq is no longer parsing the taxonomy correctly. I have tried to figure out a workaround but have not been successful. How do I change my phyloseq object to correctly parse the taxonony file for downstream analysis? This is the format of the SILVA taxonomy for your reference. "D_0__Bacteria;D_1__Fusobacteria;D_2__Fusobacteriia;D_3__Fusobacteriales;D_4__Leptotrichiaceae;D_5__Leptotrichia;D_6__Leptotrichia sp. oral clone FP036"

**Comment by jbisanz** [comment]
I will have to make the qza_to_phyloseq function a little smarter, but in the mean while please manually build your phyloseq object as per the readme.md and modify the separate command to use the split as sep=";" sans the space.

**Comment by aj-kozik** [comment]
Thanks! One more thing, In the readme instructions for building the object, where does the table.qza get imported? I see a command for the tree, the tax table, and the metadata, but not the ASV table. In this line 

physeq<-phyloseq(otu_table(otus$data, taxa_are_rows = T), phy_tree(tree$data), tax_table(tax_table), sample_data(metadata))

'otus' isn't defined.

**Comment by jbisanz** [comment]
It was in one of the higher lines:
` otus<-read_qza("~/QIIME2/mvpics/table.qza")`

**Comment by aj-kozik** [comment]
got it. thanks!
