### ISSUE TITLE
Version incompatibilities? 

### ISSUE THREAD

**Issue by zapratte** [jbisanz/qiime2R#12]
I can't seem to load the qiime2R package. I've successfully installed it, but when I try to load it, I get this error:

> library(qiime2R)
Error: package or namespace load failed for ‘qiime2R’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/.../Library/R/3.6/library/Rhdf5lib/libs/Rhdf5lib.so':
  dlopen(/Users/.../Library/R/3.6/library/Rhdf5lib/libs/Rhdf5lib.so, 6): Library not loaded: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libR.dylib
  Referenced from: /Users/.../Library/R/3.6/library/Rhdf5lib/libs/Rhdf5lib.so
  Reason: image not found

My best (somewhat inexperienced) guess is version incompatibilities? Any insight would be appreciated!

**Comment by jbisanz** [comment]
I checked this on my OS X mojave machine and I did not have this issue with 3.6.0. I am wondering if uninstalling or updating your Rhdf5lib might help `BiocManager::install("Rhdf5lib")`. I am thinking something funny happened in your update from 3.5 to 3.6.

**Comment by zapratte** [comment]
Unfortunately I get the exact same error (described above) on two different OSX machines, so it's not just an update error on one machine. I tried running BiocManager::install("Rhdf5lib") and get this:

Warning message:
package ‘Rdhf5lib’ is not available (for R version 3.6.0)

**Comment by jbisanz** [comment]
Hmm, I checked this on two more macs, a second mojave, and a high sierra and I can't replicate the error. Given that you got the error that Rdhf5lib isn't available, I wonder if you need to update your BiocManager as well. I currently have BiocManager_1.30.4 and Rhdf5lib_1.6.0. Please let me know what happens.

Jordan

**Comment by zapratte** [comment]
Got it! I had to update BiocManager and THEN Rhdf5lib, both at the System level (not the user level). Thank you!
