### ISSUE TITLE
qza_to_phyloseq doesn't handle taxonomy.qza generated using Silva

### ISSUE THREAD

**Issue by meta00** [jbisanz/qiime2R#14]
Hi @jbisanz 
`qza_to_phyloseq()` only imports correctly `taxonomy.qza` generated with Greengenes db, not Silva. Sorry I don't have the object for you but the `Taxon` in the latter case is written as, for example:

`"D_0__Bacteria;D_1__Firmicutes;D_2__Clostridia;D_3__Clostridiales;D_4__Ruminococcaceae;D_5__Ruminococcaceae NK4A214 group;D_6__uncultured bacterium"`

So lines 38 - 41 in `qza_to_phyloseq.R` is not adapted. I can do a PR, if you like.

**Comment by jbisanz** [comment]
That would be great if you could! It needs a more elegant way of detecting the separator and handling variable length taxonomic strings, but I have not had the time to address this myself.

Jordan

**Comment by nebfield** [comment]
If you're looking for a simple manual fix you can run: 

```
tax <- data.frame(phyloseq::tax_table(ps)[, 1]) %>%
  mutate(Kingdom = stringr::str_replace_all(Kingdom, "D_\\d__", ""))
tax <- tax %>%
  tidyr::separate(Kingdom, c("Kingdom", "Phylum", "Class", "Order", "Family", "Genus", "Species"), sep = ";")

tax_mat <- as.matrix(tax)
rownames(tax_mat) <- phyloseq::taxa_names(ps)
phyloseq::tax_table(ps) <- tax_mat
```

**Comment by mradz19** [comment]
Hi @nebfield 

I'm having the same issue, I've tried using your script but I can't get it to work. I get the following error:

> tax <- data.frame(phyloseq::tax_table(ps)[, 1]) %>%
+     mutate(Kingdom = stringr::str_replace_all(Kingdom, "D_\\d__", ""))
Error in phyloseq::tax_table(ps) : object 'ps' not found

Is there something I am doing wrong/am I missing a package?

**Comment by nebfield** [comment]
Hi, ps should be replaced with the name of your phyloseq object. Sorry for the confusion.

**Comment by mradz19** [comment]
Thanks @nebfield, just another question now when I run it I get an error of "cannot find function "mutate"". Is that from a specific package?

**Comment by mradz19** [comment]
Thanks @nebfield, sorry I'm new to this.

Running the script:

tax <- data.frame(phyloseq::tax_table(ps)[, 1]) %>%
  mutate(Kingdom = stringr::str_replace_all(Kingdom, "D_\\d__", ""))

I get the following error:

tax <- data.frame(phyloseq::tax_table(ps)[, 1]) %>%
  mutate(Kingdom = stringr::str_replace_all(Kingdom, "D_\\d__", ""))

Do you know what is causing this?

**Comment by nebfield** [comment]
It's hard to say. What's the output of 

```
tax <- data.frame(phyloseq::tax_table(ps)[, 1]) 
colnames(tax)
```

**Comment by mradz19** [comment]
Hi @nebfield 

The output is:

Error in is.data.frame(x) : object 'tax' not found
