### ISSUE TITLE
problem opening taxonomy file from Silva

### ISSUE THREAD

**Issue by AliceBaniel** [jbisanz/qiime2R#15]
Hi @jbisanz

qza_to_phyloseq and read_qza do not manage to open correctly my silva taxonomy file. I got a warning message (see attached). It creates the phyloseq object but the taxonomy has 8335 rows (= ASVs) instead of 34550. I converted my qza file to tsv file and checked that it contains effectively 34550 ASVs.

I think it is because there is a unusual character in row 8335. Basically the taxonomy is "D_6__[Clostridium] piliforme (Tyzzer's bacillus)". I wonder if it is because the functions can not handle the ' ? 

Could you advise on what I can do? I am happy to send you my qza file but I do not manage with this platform. 

Many thanks for your help. 

A.

![Warning message](https://user-images.githubusercontent.com/28596703/66584371-08905380-eb53-11e9-9312-1118975d91c1.png)

**Comment by jbisanz** [comment]
All fixed!
