### ISSUE TITLE
package ‘qiime2r’ is not available (for R version 3.6.2)

### ISSUE THREAD

**Issue by jessmrandall** [jbisanz/qiime2R#17]
Hi! I hope you can make this available for 3.6 soon.

Thanks!

**Comment by jbisanz** [comment]
Hi Jess,

I have it running on 3.6.1 right now, could you let me know how you are installing, any and all error messages, and the results of `sessionInfo()`?

Jordan

**Comment by jessmrandall** [comment]
so sorry, my mistake, it's all good now!
