### ISSUE TITLE
unable to import table.qza

### ISSUE THREAD

**Issue by MADscientist314** [jbisanz/qiime2R#2]
> SVs<-read_qza("table.qza")
Error in unzip(file, exdir = tmp) : 'exdir' does not exist

**Comment by MADscientist314** [comment]
I also tried manually pushing the tmp into a folder I made called "exdir" and I receive the following cmd:
> SVs<-read_qza("table.qza", tmp="exdir")
Warning message:
In read_qza("table.qza", tmp = "exdir") :
  Artifact was not generated with Qiime2 2018.4, if data is not successfully imported, please report here github.com/jbisanz/qiime2R/issues
> SVs<-read_tsv("otu_table")

**Comment by jbisanz** [comment]
Which operating system are you using and do you have permissions to write to /tmp? The default behavior is to unzip to /tmp but perhaps there is some reason you can't? The second post you made appears to have worked properly, the message that it gave you is because I didn't have access to artifacts from many earlier QIIME2 versions. It probably worked just fine.
Can you try the following and see if your data was imported properly?

```
dir.create("tmpdir")
SVs<-read_qza("table.qza", tmp="tmpdir")
SVs$data[1:10,1:3]
```

**Comment by MADscientist314** [comment]
I am using R version 3.5.0 (2018-04-23) -- "Joy in Playing"
Copyright (C) 2018 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)
It looks like it did work, as I am seeing the following:
Warning message:
In dir.create("tmpdir") : 'tmpdir' already exists
> SVs<-read_qza("table.qza", tmp="tmpdir")
Warning message:
In read_qza("table.qza", tmp = "tmpdir") :
  Artifact was not generated with Qiime2 2018.4, if data is not successfully imported, please report here github.com/jbisanz/qiime2R/issues
> SVs$data[1:10,1:3]
                                 R1c R1d R1g
d4fb52ee97d7914fef25637b243bf395  80 120  74
6c869c5d8ae26f1c1e68170ec4dce284  58  76  45
6fb75598bd9ccceeb1bd8057aeb0259e  61  59  62
1ad6a36a6933c6ae77f27e032e2e0bc0  63  65  59
6d6c398e1721d7c2939ccd1b4f9b6df8  53  70  61
16caf6b9a2116a74ef9e5480082bcbc9  52  66  53
23998200de4417166486a9c571bf4dfa 221 123 634
058f1040f6c337550b6e40d11f82e3de 627  76  74
8ded19ba3180f04fada2be334a33e2e6 221 189 144
ee60a9346bbbfd06888647558751e6ce 245 184 173

**Comment by jbisanz** [comment]
Ok, it would appear that the problem was related to a windowsism. Specifying your tmp directory should fix this issue. The warning message will stay in place for now just in case.
