### ISSUE TITLE
"Fail to install 'qiime2R' from Gitub

### ISSUE THREAD

**Issue by cortegas** [jbisanz/qiime2R#20]
Hi,
I tried to install the package the R studio through devtools and through remotes, neither of them worked. 
Here is the code that the output error

```
library(remotes) 
remotes::install_github("jbisanz/qiime2R")
```
Downloading GitHub repo jbisanz/qiime2R@master
Skipping 12 packages ahead of CRAN: Biostrings, biomformat, phyloseq, BiocGenerics, S4Vectors, IRanges, XVector, rhdf5, Biobase, multtest, zlibbioc, Rhdf5lib
Error: Failed to install 'qiime2R' from GitHub:s6gqzfn4v15p_mcs36ytm140000gn/T/RtmpDUCyxB/remotes89c2bec9f5/jbisanz-qiime2R-3fc6241/DESCRIPTION’ ...
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/prettyunits/R/prettyunits.rdb' is corrupt
In addition: Warning messages:
1: In paste0(" (", pretty_dt(elapsed), ")") :
  restarting interrupted promise evaluation
2: In paste0(" (", pretty_dt(elapsed), ")") :
  internal error -3 in R_decompress1

Same output but doing with devtools. 

```
library(devtools)
devtools::install_github("jbisanz/qiime2R")
```
Downloading GitHub repo jbisanz/qiime2R@master
Skipping 12 packages ahead of CRAN: Biostrings, biomformat, phyloseq, BiocGenerics, S4Vectors, IRanges, XVector, rhdf5, Biobase, multtest, zlibbioc, Rhdf5lib
Error: Failed to install 'qiime2R' from GitHub:s6gqzfn4v15p_mcs36ytm140000gn/T/RtmpDUCyxB/remotes89ca5a1498/jbisanz-qiime2R-3fc6241/DESCRIPTION’ ...
  lazy-load database '/Library/Frameworks/R.framework/Versions/3.6/Resources/library/prettyunits/R/prettyunits.rdb' is corrupt
In addition: Warning messages:
1: In paste0(" (", pretty_dt(elapsed), ")") :
  restarting interrupted promise evaluation
2: In paste0(" (", pretty_dt(elapsed), ")") :
  internal error -3 in R_decompress1

Does anyone had the same error or knows what is about the corrupt?

Thank you!

Stay safe.

**Comment by jbisanz** [comment]
I suspect this issue could be solved by reinstalling prettyunits as this appears to be triggering the issue. Please try `install.packages("prettyunits")` and then restart your R session before trying to reinstall using `devtools::install_github()`. Let me know how it goes,
Jordan

**Comment by cortegas** [comment]
Hi Jordan,

Perfect. It worked.

Thank you!

**Comment by jbisanz** [comment]
Great!
