### ISSUE TITLE
problem with beta diversity 

### ISSUE THREAD

**Issue by pavlo888** [jbisanz/qiime2R#24]
Hi, 

I have a problem plotting beta diversity. 

When I run the following command: 

`bray_curtis$data$Vectors %>%
  select(SampleID, PC1, PC2) %>%
  left_join(metadata) %>%
  left_join(shannon) %>%
  ggplot(aes(x=PC1, y=PC2, color=`Sampling_time`, shape=`Sampling_site`, size=shannon)) +
  geom_point(alpha=0.5) + #alpha controls transparency and helps when points are overlapping
  theme_q2r() +
  scale_shape_manual(values=c(16,1), name="Sampling_site") + #see http://www.sthda.com/sthda/RDoc/figure/graphs/r-plot-pch-symbols-points-in-r.png for numeric shape codes
  scale_size_continuous(name="Shannon Diversity") +
  scale_color_discrete(name="Sampling_time")`

I get the following error: 
`Error: `x` and `y` must share the same src, set `copy` = TRUE (may be slow).
Run `rlang::last_error()` to see where the error occurred.`

Could you please help me solve this issue? 

Cheers, 
Pablo

**Comment by jbisanz** [comment]
Is the data located on your personal computer, or are you accessing it from a remove server?

**Comment by pavlo888** [comment]
the data is located on my personal computer

**Comment by jbisanz** [comment]
This seems to be some sort of sporadic error relating to a change in (presumably) dplyr? Restarting your session and/or updating dplyr should hopefully correct the issue.
