### ISSUE TITLE
Failed to install qiime2R in R (4.0.1)

### ISSUE THREAD

**Issue by Lin936** [jbisanz/qiime2R#25]
Hello,
I am new to R and trying to install qiime2R, but seems qiime2R couldn't be installed in version 4.0.1
In this case, how to install qiime2R?

Thanks for your help
Lin

**Comment by jbisanz** [comment]
Hi Lin,

qiime2R will work in 4.0.1. Please provide details on how you tried to install it and any error messages you received.

Jordan

**Comment by Lin936** [comment]
Hi Jordan,
Thanks for your quick response.
I just tried again, but still failed.

> devtools::install_github("jbisanz/qiime2R")
Downloading GitHub repo jbisanz/qiime2R@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                     
2: CRAN packages only      
3: None                    
4: DT (0.14 -> 0.15) [CRAN]

Enter one or more numbers, or an empty line to skip updates:2
DT (0.14 -> 0.15) [CRAN]
Installing 1 packages: DT

  There is a binary version available but the source version is later:
   binary source needs_compilation
DT   0.14   0.15             FALSE

installing the source package ‘DT’

trying URL 'https://cran.rstudio.com/src/contrib/DT_0.15.tar.gz'
Content type 'application/x-gzip' length 1508722 bytes (1.4 MB)
downloaded 1.4 MB

ERROR: failed to lock directory 'C:/Program Files/R/R-4.0.1/library' for modifying
Try removing 'C:/Program Files/R/R-4.0.1/library/00LOCK-DT'
Error: Failed to install 'qiime2R' from GitHub:
  (converted from warning) installation of package ‘DT’ had non-zero exit status

I have no idea what should I do.
Lin

**Comment by Lin936** [comment]
Hi Jordan,
I deleted DT and installed it again,  now it seems ok!
Thanks Jordan.
Lin
