### ISSUE TITLE
Issues installing qiime2 R

### ISSUE THREAD

**Issue by lautaro-rostoll** [jbisanz/qiime2R#29]
Hello, 
Thanks a lot for the tutorial you created to install this package. 
I followed the tutorial to install the program, but I was not able to install it. 
Here are the commands and error that I got: 

> devtools::install_github("jbisanz/qiime2R")
Downloading GitHub repo jbisanz/qiime2R@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                              
2: CRAN packages only               
3: None                             
4: backports (1.2.0 -> 1.2.1) [CRAN]
5: dplyr     (1.0.3 -> 1.0.4) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 
√  checking for file 'C:\Users\lauta\AppData\Local\Temp\RtmpaK2itC\remotes8cc05167186\jbisanz-qiime2R-43b6bf1/DESCRIPTION' ... 
-  preparing 'qiime2R':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'qiime2R_0.99.4.tar.gz'
   
Installing package into ‘C:/Users/lauta/OneDrive - University of Florida/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
* installing *source* package 'qiime2R' ...
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error: .onLoad failed in loadNamespace() for 'checkmate', details:
  call: NULL
  error: package 'backports' does not have a namespace
Execution halted
ERROR: lazy loading failed for package 'qiime2R'
* removing 'C:/Users/lauta/OneDrive - University of Florida/Documents/R/win-library/4.0/qiime2R'
Error: Failed to install 'qiime2R' from GitHub:
  (converted from warning) installation of package ‘C:/Users/lauta/AppData/Local/Temp/RtmpaK2itC/file8cc0a9334f9/qiime2R_0.99.4.tar.gz’ had non-zero exit status

let me know if you can help to figure out what is the problem!

**Comment by lautaro-rostoll** [comment]
and before I tried this: 
> **if (!requireNamespace("devtools", quietly = TRUE)){install.packages("devtools")}
> devtools::install_github("jbisanz/qiime2R")**
Downloading GitHub repo jbisanz/qiime2R@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                              
2: CRAN packages only               
3: None                             
4: backports (1.2.0 -> 1.2.1) [CRAN]
5: dplyr     (1.0.3 -> 1.0.4) [CRAN]

Enter one or more numbers, or an empty line to skip updates:1
backports (1.2.0 -> 1.2.1) [CRAN]
dplyr     (1.0.3 -> 1.0.4) [CRAN]
Installing 2 packages: backports, dplyr
Installing packages into ‘C:/Users/lauta/OneDrive - University of Florida/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)

  There are binary versions available but the source versions are later:
          binary source needs_compilation
backports  1.2.0  1.2.1              TRUE
dplyr      1.0.3  1.0.4              TRUE

installing the source packages ‘backports’, ‘dplyr’

trying URL 'https://cran.rstudio.com/src/contrib/backports_1.2.1.tar.gz'
Content type 'application/x-gzip' length 21184 bytes (20 KB)
downloaded 20 KB

trying URL 'https://cran.rstudio.com/src/contrib/dplyr_1.0.4.tar.gz'
Content type 'application/x-gzip' length 953686 bytes (931 KB)
downloaded 931 KB

ERROR: failed to lock directory 'C:/Users/lauta/OneDrive - University of Florida/Documents/R/win-library/4.0' for modifying
Try removing 'C:/Users/lauta/OneDrive - University of Florida/Documents/R/win-library/4.0/00LOCK-backports'
Error: Failed to install 'qiime2R' from GitHub:
  (converted from warning) installation of package ‘backports’ had non-zero exit status

**Comment by jbisanz** [comment]
Hi there, this is a sporadic issue with windows that is not specific to qiime2R. It might be further aggravated by having your R libraries stored inside a microsoft onedrive sync'd folder. The solution is probably to change where you are storing your libraries but first thing first, try doing what the error message said:
```
ERROR: failed to lock directory 'C:/Users/lauta/OneDrive - University of Florida/Documents/R/win-library/4.0' for modifying
Try removing 'C:/Users/lauta/OneDrive - University of Florida/Documents/R/win-library/4.0/00LOCK-backports'
```
