### ISSUE TITLE
opening "remainder" on taxa_barplot

### ISSUE THREAD

**Issue by figbeirns** [jbisanz/qiime2R#38]
Hello, I'm very new to coding and all the info provided on this page makes processing this data so easy, so thank you! However, when I plot the taxa bar plots, I'd like it to assign colours to more than 10 species, but I don't know how to open up the "remainder" category. Any suggestions would be grea
![taxa_heatmap Bacterial](https://user-images.githubusercontent.com/94706635/142667426-9d186bed-6342-4554-804a-768bad1c6d36.png)
t!

**Comment by BisanzLab** [comment]
There is a parameter called ntoplot which you can set to higher than 10.

**Comment by figbeirns** [comment]
Ah perfect, that's done exactly what I wanted! Thank you
