### ISSUE TITLE
Error in unzip(file, exdir = tmp) : ‘exdir’ does not exist

### ISSUE THREAD

**Issue by gitIssues2018** [jbisanz/qiime2R#4]
Sorry, I think I have finally found the correct platform to submit a qiime2R issue.

Hello, I have installed the qiime2R package into R on my windows machine. I am able to successfully run commands which only have a single argument since I can designate the exdir path. The following two commands work fine.

otus<-read_qza(“table.qza” , tmp=“C:\tmp”)
otus<-read_qza(“table.qza” , tmp=“C:/tmp”)

When I run the qza_to_phyloseq command…
physeq<-qza_to_phyloseq(“table.qza”,“rooted-tree.qza”,“taxonomy.qza”, “sample-metadata.tsv”)

I receive the the error…
Error in unzip(file, exdir = tmp) : ‘exdir’ does not exist

How best can the exdir be designated in a windows R environment?

**Comment by jbisanz** [comment]
Hi there,

Apologies for the delay, I can make this option available for the qza_t

**Comment by jbisanz** [comment]
I have added the tmp argument to qza_to_phyloseq which should fix your issue on windows now.

Jordan

**Comment by gitIssues2018** [comment]
> tree<-read_qza("rooted-tree.qza")
Error in unzip(file, exdir = tmp, list = TRUE) : 
  zip file 'rooted-tree.qza' cannot be opened
In addition: Warning message:
In unzip(file, exdir = tmp) : error 1 in extracting from zip file

**Comment by jbisanz** [comment]
Can you create a new folder in your current working directory called testfolder then try with tmp="testfolder" and tell me if it still is throwing an error? My apologies I do not have a windows (i'm assuming its windows) machine to test on.

**Comment by jbisanz** [comment]
specifically try:
```
dir.create("testfolder")
tree<-read_qza("rooted-tree.qza", tmp="testfolder")
```
