### ISSUE TITLE
Phyloseq object not recognizing negative control 

### ISSUE THREAD

**Issue by Avtober** [jbisanz/qiime2R#40]
Hi there

When I try to make a phyloseq object with the following code, the phyloseq object seems to only recognise the samples not the negative controls. Does anyone know why this may be happening? I have the names of the controls in my metadata file so they should be coming up.

library("qiime2R")
physeq3<-qza_to_phyloseq(
features="DADA2-table4andneg.qza",
tree="rooted-tree4andneg.qza",
"NCBI_LSURef_97_10_uniq_5-8-300_classification_VSEARCHwithneg.qza",
metadata = "metadata-2.txt")
physeq3

Thanks

**Comment by Avtober** [comment]
Hi, just to add to this when I import the files separately using read_qza I can see the negative is in there but it is just when I use the qza_to_phyloseq that it does not seem to recognize it as a sample. Is there a way to just read the files in using read_qza then combining these files into a phyloseq object? 

Thanks 
A

**Comment by jbisanz** [comment]
Do the negative controls have reads assigned to them? I wonder if phyloseq is stripping them out.
