### ISSUE TITLE
summarize_taxa

### ISSUE THREAD

**Issue by andrneves** [jbisanz/qiime2R#49]
Hello,

I used summarize_taxa to give me the sum of the counts, but the function returned the wrong sum by placing the results in column P168.
The data is attached.

Would you happen to have any suggestions to fix this issue?

The code used is:

taxonomy <- read_qza ("taxonomy.qza")$data %>% parse_taxonomy()
SVs<-read_qza("table.qza")$data
abundance <- summarize_taxa(SVs, taxonomy)$Genus
view(abundance)

Thanks.

[SVs.csv](https://github.com/jbisanz/qiime2R/files/11720903/SVs.csv)
[taxonomy.csv](https://github.com/jbisanz/qiime2R/files/11720908/taxonomy.csv)

**Comment by andrneves** [comment]
My code:
taxonomy <- read_qza ("taxonomy.qza")$data %>% parse_taxonomy()
SVs<-read_qza("table.qza")$data
abundance <- summarize_taxa(SVs, taxonomy)$Genus
view(abundance)

The data is attached. 
[taxonomy.csv](https://github.com/jbisanz/qiime2R/files/11720865/taxonomy.csv)
[SVs.csv]
(https://github.com/jbisanz/qiime2R/files/11720867/SVs.csv)

Thanks.

**Comment by jbisanz** [comment]
Not a bug, answered in qiime2 forum: https://forum.qiime2.org/t/about-summarize-taxa-qiime2r/26755
