### ISSUE TITLE
Problem installing qiime2R in R 4.3.1

### ISSUE THREAD

**Issue by Anaherasm** [jbisanz/qiime2R#54]
Hello,

i am writing here because I'm having some issues installing qiime2R. I have tried other solutions (such as avoiding OneDrive or installing the programs lacking) but it was unsuccesfull...

Here is the code I used

_library(devtools)
devtools::install_github("jbisanz/qiime2R")_ 

And here the message I obtained

_Error: Failed to install 'qiime2R' from GitHub:
  Does not appear to be an R package (no DESCRIPTION)
Además: Warning message:
In utils::untar(tarfile, ...) :
  ‘tar.exe -xf "C:\Users\Ana\AppData\Local\Temp\RtmpGW9aBl\file1d041dc46e1e.tar.gz" -C "C:/Users/Ana/AppData/Local/Temp/RtmpGW9aBl/remotes1d043d833bea"’ returned error code 1_

Thank you all in advance!

**Comment by jbisanz** [comment]
I think the answer lies here: `In utils::untar(tarfile, ...) :
‘tar.exe -xf "C:\Users\Ana\AppData\Local\Temp\RtmpGW9aBl\file1d041dc46e1e.tar.gz" -C "C:/Users/Ana/AppData/Local/Temp/RtmpGW9aBl/remotes1d043d833bea"’ returned error code 1` . Not 100% sure what the source of this would be but this wouldn't be related to qiime2R itself. I would start by changing the install location of your R libraries and trying reinstallation.
