### ISSUE TITLE
QZA to FASTA? 

### ISSUE THREAD

**Issue by hank00000** [jbisanz/qiime2R#55]
A colleague sent me a qza file containing trimmed reads. I use qiime2r in other projects where they send me the finished assigned product, but this time it's only the trimmed reads. I know in qiime2 you can export qza as fasta, but I like qiime2r because this way I never have to download qiime2 and I can just got through R. Is there a way in this package that I can take a qza and get fasta files for dada2 input?

**Comment by jbisanz** [comment]
This functionality could be added in, but perhaps the easiest thing is to unzip the artifact and find the files yourself to feed into dada2. Something like this:

```
unzip("yourreads.qza", "unpacked_reads")
forward<-list.files("unpacked_reads", pattern="_R1_", full.names=TRUE)
reverse<-list.files("unpacked_reads", pattern="_R2_", full.names=TRUE)
```
