### ISSUE TITLE
Phyloseq Object have 0 in OTU table

### ISSUE THREAD

**Issue by lingvv** [jbisanz/qiime2R#56]
Hello!
Thank you for creating this helpful tool; it has been truly beneficial.

I would like to confirm if it's expected for my phyloseq object to contain all zeros in the OTU table. I am certain that my OTU table is not empty. 
Thank you for your assistance.

My phyloseq object
```
phyloseq-class experiment-level object
otu_table()   OTU Table:         [ 1663 taxa and 48 samples ]
sample_data() Sample Data:       [ 48 samples by 4 sample variables ]
tax_table()   Taxonomy Table:    [ 1663 taxa by 7 taxonomic ranks ]
phy_tree()    Phylogenetic Tree: [ 1663 tips and 1656 internal nodes ]
```

![image](https://github.com/jbisanz/qiime2R/assets/148859014/afeff51b-b914-443b-96ad-5659770e6252)

**Comment by jbisanz** [comment]
Is it actually all zeros, or is that just the first set of values shown in that preview? You should probably check the sum, rowSums, and colSums of your table.

**Comment by lingvv** [comment]
I've examined my `phyloseq` object using `taxa_sums(ps) [1:10]`, and it appears not to be empty.
My apologies for any confusion caused, and thank you for your prompt response!

However, if you wouldn't mind, could you also provide a guidance to this question? https://github.com/jbisanz/qiime2R/issues/57  
Your assistance is greatly appreciated.

```
> taxa_sums(ps) [1:10]
35e6f4ecc89cd35bd8cc71e6b6a5e87d 
                               2 
6af84e470dc6b2f69701b4e9bcf525d6 
                               9 
73799d5308d251a337e717da4604a2b8 
                               5 
3967519d7c2705c72c8884b7f3a34edb 
                              21 
c0791b6e15722cc74e740ecf4e62fe8a 
                              64 
24ccde73595ce75382cd60122d05b774 
                              64 
988228c6d9b56d5f03225e60d406a64e 
                              28 
22b9fb3d47b0ce3b1adad22497f8258e 
                               5 
a03e5bdad15ab78ea408f5a2ed816d52 
                               6 
02c5af34088fb0b9cd27b8fcea1856c9 
                               4 
```
