### ISSUE TITLE
Support R 3.4.1?

### ISSUE THREAD

**Issue by tanaes** [jbisanz/qiime2R#6]
Would it be at all possible to change this package to support R version 3.4.1, which is the version currently installed by qiime2? This would enable qiime2R to be installed directly in the qiime2 Conda environment, which I bet many people would find helpful. 

I'm having some hairy dependency issues surrounding hdf5 libraries, and currently facing a situation where I am able to get biomformat to read biom files in 3.4.1 but not 3.5. 

What do you think?

**Comment by jbisanz** [comment]
This is a good idea, I have changed the dependency and also made sure that the pre-req package versions match what is installed into that version of R 3.4.1 inside my conda qiime2-2018.11 environment.

**Comment by tanaes** [comment]
It worked! It worked! It worked! You're a hero! Thank you!
