### ISSUE TITLE
Support for TreeSummarizedExperiment container?

### ISSUE THREAD

**Issue by antagomir** [jbisanz/qiime2R#60]
[TreeSummarizedExperiment](https://f1000research.com/articles/9-1246/v2) has emerged as an alternative to phyloseq in R/Bioconductor, using the new SummarizedExperiment container family. There are now couple packages supporting this, e.g. such as curatedMetagenomicData, EBI/MGnify, ANCOMBC etc. 

If the qiime2R package is in active stage, we could open a PR adding support to `TreeSummarizedExperiment`. This could be similar to the current function [qiime2R::qza_to_phyloseq](https://github.com/jbisanz/qiime2R/blob/master/R/qza_to_phyloseq.R) i.e. we could contribute `qiime2R::qza_to_treese` or `qiime2R::qza_to_treesummarizedexperiment`. This would support linking with an alternative R/Bioc microbiome ecosystem.

**Comment by jbisanz** [comment]
That sounds like a great idea! Let me know if you want any assistance.

**Comment by antagomir** [comment]
In practice, this could mean two things to add:

1. `qza_to_tse()` (similar to the already available `qza_to_phyloseq()`)
2. Adding an example to README (in addition to the already available phyloseq example).
3. Cross-linking to external documentation resources that utilize TreeSE (e.g. OMA gitbook)

We are suggesting a PR soon.

**Comment by antagomir** [comment]
Or perhaps not necessary as the PR is already open. I can comment here directly.

**Comment by Insaynoah** [comment]
I did fork it. Here you can see the function I added [https://github.com/Insaynoah/qiime2R/blob/master/R/qza_to_tse.R](https://github.com/Insaynoah/qiime2R/blob/master/R/qza_to_tse.R) 

and here's the updated readme file with an example and a link to the oma book : [https://github.com/Insaynoah/qiime2R/blob/master/README.md](https://github.com/Insaynoah/qiime2R/blob/master/README.md)

Thanks in advance for checking.

**Comment by antagomir** [comment]
Solved in #64 - thanks for all!
