### ISSUE TITLE
qiime2R error in download, install? R v 4.4.1

### ISSUE THREAD

**Issue by nathanfrazier35** [jbisanz/qiime2R#70]
Good day! I am having an issue with downloading/installing qiime2R. I either get the following error message:

#########
> install.packages("qiime2R")
WARNING: Rtools is required to build R packages but is not currently installed. Please download and install the appropriate version of Rtools before proceeding:

https://cran.rstudio.com/bin/windows/Rtools/
Installing package into ‘C:/Users/Anthony.Frazier/AppData/Local/R/win-library/4.4’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘qiime2R’ is not available for this version of R

A version of this package for your version of R might be available elsewhere,
see the ideas at
https://cran.r-project.org/doc/manuals/r-patched/R-admin.html#Installing-packages
#########

Or I get this:

#########
> devtools::install_github("jbisanz/qiime2R")
Downloading GitHub repo jbisanz/qiime2R@HEAD
Skipping 17 packages ahead of CRAN: S4Vectors, BiocGenerics, zlibbioc, XVector, GenomeInfoDbData, GenomeInfoDb, IRanges, Biobase, MatrixGenerics, rhdf5filters, Rhdf5lib, rhdf5, treeio, Biostrings, multtest, biomformat, phyloseq
Installing 8 packages: SparseArray, DelayedArray, S4Arrays, GenomicRanges, SummarizedExperiment, BiocParallel, SingleCellExperiment, TreeSummarizedExperiment
Installing packages into ‘C:/Users/Anthony.Frazier/AppData/Local/R/win-library/4.4’
(as ‘lib’ is unspecified)
Warning: unable to access index for repository https://bioconductor.org/packages/3.18/bioc/bin/windows/contrib/4.4:
  cannot open URL 'https://bioconductor.org/packages/3.18/bioc/bin/windows/contrib/4.4/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.18/data/annotation/bin/windows/contrib/4.4:
  cannot open URL 'https://bioconductor.org/packages/3.18/data/annotation/bin/windows/contrib/4.4/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.18/data/experiment/bin/windows/contrib/4.4:
  cannot open URL 'https://bioconductor.org/packages/3.18/data/experiment/bin/windows/contrib/4.4/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.18/workflows/bin/windows/contrib/4.4:
  cannot open URL 'https://bioconductor.org/packages/3.18/workflows/bin/windows/contrib/4.4/PACKAGES'
Warning: unable to access index for repository https://bioconductor.org/packages/3.18/books/bin/windows/contrib/4.4:
  cannot open URL 'https://bioconductor.org/packages/3.18/books/bin/windows/contrib/4.4/PACKAGES'
Packages which are only available in source form, and may need compilation of C/C++/Fortran: ‘SparseArray’
  ‘DelayedArray’ ‘S4Arrays’ ‘GenomicRanges’ ‘BiocParallel’
  These will not be installed
installing the source packages ‘SummarizedExperiment’, ‘SingleCellExperiment’, ‘TreeSummarizedExperiment’

trying URL 'https://bioconductor.org/packages/3.18/bioc/src/contrib/SummarizedExperiment_1.32.0.tar.gz'
Content type 'application/gzip' length 686052 bytes (669 KB)
downloaded 669 KB

trying URL 'https://bioconductor.org/packages/3.18/bioc/src/contrib/SingleCellExperiment_1.24.0.tar.gz'
Content type 'application/gzip' length 985002 bytes (961 KB)
downloaded 961 KB

trying URL 'https://bioconductor.org/packages/3.18/bioc/src/contrib/TreeSummarizedExperiment_2.10.0.tar.gz'
Content type 'application/gzip' length 1135547 bytes (1.1 MB)
downloaded 1.1 MB

ERROR: dependencies 'GenomicRanges', 'S4Arrays', 'DelayedArray' are not available for package 'SummarizedExperiment'
* removing 'C:/Users/Anthony.Frazier/AppData/Local/R/win-library/4.4/SummarizedExperiment'
ERROR: dependencies 'SummarizedExperiment', 'GenomicRanges', 'DelayedArray' are not available for package 'SingleCellExperiment'
* removing 'C:/Users/Anthony.Frazier/AppData/Local/R/win-library/4.4/SingleCellExperiment'
ERROR: dependencies 'SingleCellExperiment', 'SummarizedExperiment', 'BiocParallel' are not available for package 'TreeSummarizedExperiment'
* removing 'C:/Users/Anthony.Frazier/AppData/Local/R/win-library/4.4/TreeSummarizedExperiment'

The downloaded source packages are in
	‘C:\Users\Anthony.Frazier\AppData\Local\Temp\Rtmp2flPVu\downloaded_packages’
── R CMD build ──────────────────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file 'C:\Users\Anthony.Frazier\AppData\Local\Temp\Rtmp2flPVu\remotes7d4029222188\jbisanz-qiime2R-d0610e1/DESCRIPTION' ... 
─  preparing 'qiime2R': (1.5s)
✔  checking DESCRIPTION meta-information ...
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted 'LazyData' from DESCRIPTION
─  building 'qiime2R_0.99.6.tar.gz'
   
Installing package into ‘C:/Users/Anthony.Frazier/AppData/Local/R/win-library/4.4’
(as ‘lib’ is unspecified)
ERROR: dependency 'TreeSummarizedExperiment' is not available for package 'qiime2R'
* removing 'C:/Users/Anthony.Frazier/AppData/Local/R/win-library/4.4/qiime2R'
Warning messages:
1: In i.p(...) :
  installation of package ‘SummarizedExperiment’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘SingleCellExperiment’ had non-zero exit status
3: In i.p(...) :
  installation of package ‘TreeSummarizedExperiment’ had non-zero exit status
4: In i.p(...) :
  installation of package ‘C:/Users/ANTHON~1.FRA/AppData/Local/Temp/Rtmp2flPVu/file7d4034f94679/qiime2R_0.99.6.tar.gz’ had non-zero exit status
########

If anyone can help I would be more than grateful. Thank you.

Nathan

**Comment by jbisanz** [comment]
This appears to be an issue with the installation of dependencies. Trying going one at a time to install SummarizedExperiment, SingleCellExperiment, and TreeSummarizedExperiment and see if you are able to install, and/or diagnose their issue.
